### ISSUE TITLE
LinkedIn share URL and ampersand encoding

### ISSUE THREAD

**Issue by joannaskao** [Financial-Times/o-share#66]
Hi! When I use the LinkedIn o-share button, the ampersand sign separating query parameters is encoded so that it comes out as "&amp;". LinkedIn seems to have trouble recognizing share URLs when the ampersand preceding the URL parameter is encoded in that way. Do you have any ideas for why I'm getting this error?

**Comment by callumlocke** [comment]
Something is getting double-encoded. For example if you select the Twitter share button [from here](https://ig.ft.com/us-elections/) and do `$0.outerHTML` in the console, you get this:

```html
<a href="https://twitter.com/intent/tweet?url=https://ig.ft.com/us-elections/&amp;am…linton%2044.1%25%2C%20Trump%2044.3%25&amp;amp;related=%40ft&amp;amp;via=FT"><i></i></a>
```

(notice double-encoding `&amp;amp;`)

**Comment by callumlocke** [comment]
I think it's because [these lines](https://github.com/Financial-Times/o-share/blob/master/src/js/share.js#L7-L13) have everything manually HTML-encoded, but it doesn't need to be; it gets escaped again when it gets set as the href for the link [here](https://github.com/Financial-Times/o-share/blob/master/src/js/share.js#L155).
